[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "certbot-dns-simply"
version = "0.1.3"
description = "Simply.com DNS Authenticator plugin for Certbot"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "Johan Nenzén", email = "johan.nanzen@gmail.com"},
]
urls = { "Homepage" = "https://github.com/JohNan/certbot-dns-simply" }
requires-python = ">=3.10"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Security",
    "Topic :: System :: Installation/Setup",
    "Topic :: System :: Networking",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
]

dependencies = [
    "certbot",
    "requests",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "requests-mock",
    "tox",
    "pre-commit",
]

[project.entry-points."certbot.plugins"]
"dns-simply" = "certbot_dns_simply.dns_simply:Authenticator"

[tool.setuptools.packages]
find = {}

[tool.setuptools]
include-package-data = true
